version: '3'

services:
  app:
    build:
      args:
        app_port: "${APP_PORT}"
      context: .
      dockerfile: ./build/app/Dockerfile
    expose:
      - "${APP_PORT}"
  tests:
    build:
      context: .
      dockerfile: ./build/tests/Dockerfile
    depends_on:
      - app

